name: .NET-Test-6x

on:
  push:
    branches: [ '2.0' ]
  pull_request:
    branches: [ '2.0' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
    - name: Restore dependencies
      run: dotnet restore UnitTest
    - name: Build-6.0
      run: dotnet build --framework net6.0 --no-restore UnitTest
    - name: Test-6.0
      run: dotnet test --framework net6.0 --no-build --verbosity normal --filter "ClassName!='SkiaImageTests'&ClassName!='GraphicsTests'" UnitTest
